alias la='ls -lahrt --color=always | awk '\''{print $5"\t"$6" "$7"\t"$8" "$9}'\'''
alias gs='git status'
alias ga='git add'
alias gd='git diff'
alias gap='git add --patch'
alias gc='git commit'
alias gp='git push'
alias gpsu='git push --set-upstream'
alias gb='git branch'
alias gba='git branch -a'
alias gchk='git checkout'
alias gg='git log --all --decorate --oneline --graph'
alias gl='git log'
alias gr='git remote'
alias kp='kill -9 $(ps -u $(whoami) | grep python | sort | head -1 | awk '\''{print $1}'\'')'
alias calc='localc'
alias excel='localc'
alias word='lowriter'
alias ppt='loimpress'
alias pdf='xdg-open'
alias term='gnome-terminal'
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state|time\ to\ empty|time\ to\ full|percentage"'

